---
- name: Prepare AWX Server Prerequisites
  hosts: awx_server
  become: true
  gather_facts: true

  tasks:
    - name: Update system packages
      ansible.builtin.dnf:
        name: "*"
        state: latest
        update_cache: true
      tags: update

    - name: Install required packages
      ansible.builtin.dnf:
        name:
          - epel-release
          - python3
          - python3-pip
          - git
          - curl
          - wget
          - vim
          - net-tools
          - firewalld
          - policycoreutils-python-utils
        state: present
      tags: packages

    - name: Install Docker prerequisites
      ansible.builtin.dnf:
        name:
          - yum-utils
          - device-mapper-persistent-data
          - lvm2
        state: present
      tags: docker

    - name: Add Docker repository
      ansible.builtin.command:
        cmd: dnf config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
        creates: /etc/yum.repos.d/docker-ce.repo
      tags: docker

    - name: Install Docker
      ansible.builtin.dnf:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: present
      tags: docker

    - name: Start and enable Docker service
      ansible.builtin.systemd:
        name: docker
        state: started
        enabled: true
      tags: docker

    - name: Add vagrant user to docker group
      ansible.builtin.user:
        name: vagrant
        groups: docker
        append: true
      tags: docker

    - name: Install Docker Compose standalone
      ansible.builtin.get_url:
        url: "https://github.com/docker/compose/releases/download/v{{ docker_compose_version }}/docker-compose-linux-x86_64"
        dest: /usr/local/bin/docker-compose
        mode: '0755'
      tags: docker

    - name: Configure SELinux to permissive mode
      ansible.posix.selinux:
        policy: targeted
        state: "{{ selinux_state }}"
      tags: selinux

    - name: Start and enable firewalld
      ansible.builtin.systemd:
        name: firewalld
        state: started
        enabled: true
      tags: firewall

    - name: Configure firewall for AWX
      ansible.posix.firewalld:
        port: "{{ item }}"
        permanent: true
        state: enabled
        immediate: true
      loop: "{{ firewall_ports }}"
      tags: firewall

    - name: Create AWX directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        mode: '0755'
        owner: root
        group: root
      loop:
        - "{{ docker_compose_dir }}"
        - "{{ awx_project_dir }}"
        - "{{ postgres_data_dir }}"
      tags: directories

    - name: Install Python Docker module
      ansible.builtin.pip:
        name:
          - docker
          - docker-compose
        state: present
      tags: python

    - name: Verify Docker installation
      ansible.builtin.command:
        cmd: docker --version
      register: docker_version
      changed_when: false
      tags: verify

    - name: Display Docker version
      ansible.builtin.debug:
        msg: "Docker version: {{ docker_version.stdout }}"
      tags: verify

    - name: Verify Docker Compose installation
      ansible.builtin.command:
        cmd: docker-compose --version
      register: compose_version
      changed_when: false
      tags: verify

    - name: Display Docker Compose version
      ansible.builtin.debug:
        msg: "Docker Compose version: {{ compose_version.stdout }}"
      tags: verify

    - name: Reboot message
      ansible.builtin.debug:
        msg: "Prerequisites installed. A reboot may be required for all changes to take effect."
      tags: always