---
- name: Distribute AWX SSH Key to Client Nodes
  hosts: clients
  become: true
  gather_facts: true

  vars:
    awx_server_ip: "192.168.56.10"

  tasks:
    - name: Ensure root .ssh directory exists on AWX server
      ansible.builtin.file:
        path: /root/.ssh
        state: directory
        mode: '0700'
      delegate_to: awx-server
      run_once: true
      tags: fetch

    - name: Check if AWX public key exists
      ansible.builtin.stat:
        path: /root/.ssh/awx_rsa.pub
      register: awx_key_stat
      delegate_to: awx-server
      run_once: true
      tags: fetch

    - name: Generate SSH key pair for AWX if it doesn't exist
      ansible.builtin.command:
        cmd: ssh-keygen -t rsa -b 4096 -f /root/.ssh/awx_rsa -N '' -C 'AWX SSH Key'
        creates: /root/.ssh/awx_rsa
      delegate_to: awx-server
      when: not awx_key_stat.stat.exists
      run_once: true
      tags: fetch

    - name: Set correct permissions on private key
      ansible.builtin.file:
        path: /root/.ssh/awx_rsa
        mode: '0600'
        owner: root
        group: root
      delegate_to: awx-server
      run_once: true
      tags: fetch

    - name: Set correct permissions on public key
      ansible.builtin.file:
        path: /root/.ssh/awx_rsa.pub
        mode: '0644'
        owner: root
        group: root
      delegate_to: awx-server
      run_once: true
      tags: fetch

    - name: Fetch AWX public key from AWX server
      ansible.builtin.slurp:
        src: /root/.ssh/awx_rsa.pub
      register: awx_pub_key
      delegate_to: awx-server
      run_once: true
      tags: fetch

    - name: Ensure .ssh directory exists for vagrant user
      ansible.builtin.file:
        path: /home/vagrant/.ssh
        state: directory
        owner: vagrant
        group: vagrant
        mode: '0700'
      tags: ssh

    - name: Add AWX public key to vagrant authorized_keys
      ansible.builtin.authorized_key:
        user: vagrant
        key: "{{ awx_pub_key.content | b64decode }}"
        state: present
        comment: "AWX Server Key"
        exclusive: false
      tags: ssh

    - name: Ensure .ssh directory exists for demo user
      ansible.builtin.file:
        path: /home/{{ demo_user }}/.ssh
        state: directory
        owner: "{{ demo_user }}"
        group: "{{ demo_user }}"
        mode: '0700'
      tags: ssh

    - name: Add AWX public key to demo user authorized_keys
      ansible.builtin.authorized_key:
        user: "{{ demo_user }}"
        key: "{{ awx_pub_key.content | b64decode }}"
        state: present
        comment: "AWX Server Key"
        exclusive: false
      tags: ssh

    - name: Test SSH connection from AWX server to vagrant user
      ansible.builtin.command:
        cmd: ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -i /root/.ssh/awx_rsa vagrant@{{ ansible_host }} echo "Connection successful"
      delegate_to: awx-server
      register: ssh_test
      changed_when: false
      failed_when: false
      tags: test

    - name: Display SSH test result
      ansible.builtin.debug:
        msg:
          - "SSH connection test to {{ inventory_hostname }} ({{ ansible_host }})"
          - "Result: {{ 'SUCCESS' if ssh_test.rc == 0 else 'FAILED' }}"
          - "Output: {{ ssh_test.stdout if ssh_test.rc == 0 else ssh_test.stderr }}"
      tags: test

    - name: Create AWX connection info file
      ansible.builtin.copy:
        content: |
          AWX Server Connection Information
          ==================================
          
          AWX Server IP: {{ awx_server_ip }}
          Client Node: {{ inventory_hostname }}
          Client IP: {{ ansible_host }}
          
          SSH Key has been distributed successfully.
          AWX can now manage this node.
          
          Test connection from AWX server:
          ssh -i /root/.ssh/awx_rsa vagrant@{{ ansible_host }}
          
          For Kubernetes AWX:
          1. Copy the private key from awx-server:
             vagrant ssh awx-server
             sudo cat /root/.ssh/awx_rsa
          2. Add it to your AWX credential in Kubernetes
        dest: /opt/awx-demo/connection-info.txt
        mode: '0644'
      tags: info

    - name: Display key location for Kubernetes AWX
      ansible.builtin.debug:
        msg:
          - "SSH keys have been generated and distributed!"
          - ""
          - "For Kubernetes AWX deployment:"
          - "1. Get the private key: vagrant ssh awx-server -c 'sudo cat /root/.ssh/awx_rsa'"
          - "2. Get the public key: vagrant ssh awx-server -c 'sudo cat /root/.ssh/awx_rsa.pub'"
          - "3. Add the private key to your AWX Machine Credential in Kubernetes"
          - ""
          - "Client nodes are ready to be managed at:"
          - "  - client-alma: 192.168.56.11"
          - "  - client-ubuntu: 192.168.56.12"
          - "  - client-centos: 192.168.56.13"
      run_once: true
      tags: info